Registered/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
import settings
from django.conf.urls.static import static
import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^nested_admin/', include('nested_admin.urls')),
    url(r'^operacion/', include('operacion.urls',namespace='operacion')),
    url(r'^usuario/', include('usuario.urls',namespace='usuario')),
    url(r'^empresa/', include('empresa.urls',namespace='empresa')),
    url(r'^motorizado/', include('motorizado.urls',namespace='motorizado')),
    url(r'^reporte/', include('reporte.urls',namespace='reporte')),
    url(r'^$', login_required(views.Index.as_view()),name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empresa/urls.py
from django.conf.urls import url
import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required


#Manejo de empresa
urlpatterns = [
    url(r'list/empresa/$', login_required(views.ListEmpresa.as_view()), name='list_empresa'),
    url(r'add/empresa/$', login_required(views.AddEmpresa.as_view()), name='add_empresa'),
    url(r'edit/empresa/(?P<pk>\d+)/$', login_required(views.EditEmpresa.as_view()), name='edit_empresa'),
    url(r'change/pass/empresa/$', login_required(views.SetPassWordEmpresa.as_view()), name='change_pass_empresa'),
    url(r'delete/empresa/(?P<pk>\d+)/$', login_required(views.DeleteEmpresa.as_view()), name='delete_pass_empresa'),
]

#Manejo de tienda
urlpatterns += [
    url(r'list/tienda/$', login_required(views.ListTienda.as_view()), name='list_tienda'),
    url(r'add/tienda/$', login_required(views.AddTienda.as_view()), name='add_tienda'),
    url(r'edit/tienda/(?P<pk>\d+)/$', login_required(views.AddTienda.as_view()), name='edit_tienda'),
    url(r'delete/tienda/(?P<pk>\d+)/$', login_required(views.DeleteTienda.as_view()), name='delete_pass_tienda'),
]

#Manejo de tienda
urlpatterns += [
    url(r'list/supervisor/$', login_required(views.ListSupervisor.as_view()), name='list_supervisor'),
    url(r'add/supervisor/$', login_required(views.AddSupervisor.as_view()), name='add_supervisor'),
    url(r'edit/supervisor/(?P<pk>\d+)/$', login_required(views.EditSupervisor.as_view()), name='edit_supervisor'),
    url(r'delete/supervisor/(?P<pk>\d+)/$', login_required(views.DeleteSupervisor.as_view()), name='delete_pass_supervisor'),
]

#Manejo de ciudad
urlpatterns += [
    url(r'list/ciudad/$', login_required(views.ListCiudad.as_view()), name='list_ciudad'),
]

#vista
urlpatterns += [
    url(r'indexEmpresas/$',login_required(views.Empresas.as_view()), name='index_empresas'),
]

#vista Tiendas
urlpatterns += [
    url(r'indexTienda/$',login_required(views.Tiendas.as_view()), name='index_tiendas'),
]

#vista Supervisores
urlpatterns += [
    url(r'indexsupervisor/$',login_required(views.Supervisores.as_view()), name='index_supervisor'),
]

reporte/urls.py
from django.conf.urls import url
import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
#Inicio de session
urlpatterns = [
    url(r'^pagos/$',login_required(views.Pagos.as_view()), name='pagos'),
    url(r'^home/pagos/$',login_required(views.Reporte.as_view()), name='reportes'),
]

#
urlpatterns += [
    url(r'^ws/pagos/empledos/$',login_required(views.WsPagosEmpleados.as_view()), name='ws_pagos'),
]


#reporte depagos
urlpatterns += [
    url(r'^ws/pagos/empledos/imprimir/$',login_required(views.WsPagosEmpleadosImprimir.as_view()), name='ws_pagosg'),
]

#reporte depagos
urlpatterns += [
    url(r'^pagos/empledo/especifico/imprimir/$',login_required(views.EmpleadoEspicificoImprimir.as_view()), name='ws_pagose'),
]

usuario/urls.py
from django.conf.urls import url
import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

#empleado
urlpatterns = [
    url(r'^login/empleado/$',login_required(views.LoginEmpleado.as_view()) ,name='login_empleado'),
    url(r'^add/empleado/$',login_required(views.AddEmpleado.as_view()) ,name='add_empleado'),
    url(r'^edit/empleado/(?P<pk>\d+)/$',login_required(views.EditEmpleado.as_view()) ,name='edit_empleado'),
    url(r'^delete/empleado/(?P<pk>\d+)/$',login_required(views.DeleteEmpleado.as_view()) ,name='delete_empleado'),
    url(r'^list/empleado/',login_required(views.ListEmpleado.as_view()) ,name='lis_empleado'),
    url(r'^list/empleados/',login_required(views.ListEmpleados.as_view()) ,name='list_empleados'),
    url(r'^change/pass/empleados/',login_required(views.SetPassWordEmpleado.as_view()) ,name='set_pass_empleado'),
    url(r'^is/login/administrador/$',login_required(views.IsLogin.as_view()) ,name='is_login_admin'),
]


#direccionamientos del empleado a nivel de vista
urlpatterns += [
    url(r'^view/empleados/$',login_required(views.GeneralCliente.as_view()), name='view_empleados'),
]


#Inicio de session
urlpatterns += [
    url(r'^login/$',views.Login.as_view(), name='login'),
    url(r'^logout/$',views.Logout.as_view(), name='logout'),
]


# manejo de usuario de empleados escritorio
urlpatterns += [
    url(r'^empleados/$',login_required(views.Empleados.as_view()), name='esc_lis_empleados'),
]


# registro de supervisores
urlpatterns += [
    url(r'^supervisores/$',login_required(views.Supervisores.as_view()), name='supervisoress'),
]

reporte/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

reporte/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from supra import views as supra
import models
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views import generic
from django.views.generic.edit import UpdateView
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from cuser.middleware import CuserMiddleware
from django.views.generic import View, DeleteView
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, get_object_or_404, HttpResponse
from empresa import models as empresa
from easy_pdf.views import PDFTemplateView
from django.utils import timezone
from datetime import datetime,timedelta
from usuario import models as usuario
from django.db.models import Q
from django.db import connection
import json as simplejson

# Create your views here.

class Pagos(TemplateView):
    def dispatch(self, request, *args, **kwargs):
        user = CuserMiddleware.get_user()
        emp = empresa.Empresa.objects.filter(supervisor__id=user.id,active=True)
        return render(request, 'reporte/pagos.html',{'empresa':emp})
    # end def
# end class


class Reporte(TemplateView):
    def dispatch(self, request, *args, **kwargs):
        return render(request, 'reporte/reportes.html')
    # end def
# end class

def producirFecha(v):
    if v :
        r = v.split('/')
        return '%s-%s-%s'%(r[2],r[1],r[0])
    #end if
    r = datetime.today()
    return '%d-%d-%d'%(r.year,r.month,r.day)
#end def

class WsPagosEmpleados(View):
    def get(self, request):
        print 'llego 1'
        empresa = request.GET.get('empresa', '0')
        ciudad = request.GET.get('ciudad', '0')
        tienda = request.GET.get('tienda', '0')
        inicio = producirFecha(request.GET.get('inicio', '11/09/2017'))
        fecha = datetime.today()
        #fin = producirFecha(request.GET.get('fin', '%d/%d/%d'%(fecha.day,fecha.month,fecha.year)))
        fin = producirFecha(request.GET.get('25/09/2017', '30/09/2017'))
        busqueda = request.GET.get('busqueda', '')
        cursor = connection.cursor()
        m = 'select get_total_trabajador2(%d,\'%s\'::text,%s::integer,%s::integer,%s::integer,\'%s\'::date,\'%s\'::date)' % (
            request.user.id, busqueda, empresa, ciudad, tienda, inicio, fin)
        #cursor.execute('select get_labores();')
        cursor.execute(m)
        row = cursor.fetchone()
        return HttpResponse((simplejson.dumps(row[0])), content_type="application/json")
    # end class
# end class


class WsPagosEmpleados(View):
    def get(self, request):
        print 'llego 2'
        empresa = request.GET.get('empresa', '0')
        ciudad = request.GET.get('ciudad', '0')
        tienda = request.GET.get('tienda', '0')
        fecha = datetime.today() + timedelta(days=1)
        inicio = request.GET.get('inicio','%d/%d/%d'%(fecha.day,fecha.month,fecha.year))
        fin = request.GET.get('fin', '%d/%d/%d'%(fecha.day,fecha.month,fecha.year))
        busqueda = request.GET.get('busqueda', '')
        print inicio,'  ',fin,request.GET,
        cursor = connection.cursor()
        m = 'SET datestyle = "ISO, DMY";select get_total_trabajador2(%d,\'%s\'::text,%s::integer,%s::integer,%s::integer,\'%s\'::date,\'%s\'::date)' % (
            request.user.id, busqueda, empresa, ciudad, tienda, inicio, fin)
        print m
        cursor.execute(m)
        row = cursor.fetchone()
        return HttpResponse((simplejson.dumps(row[0])), content_type="application/json")
    # end class
# end class

class WsPagosEmpleadosImprimir(PDFTemplateView):
    template_name = "reporte/pagosgeneral.html"

    def get(self, request, *args, **kwargs):
        empleados=','.join( x for x in map(str, request.GET.getlist('reporte','')))
        print empleados
        empresa = request.GET.get('empresa', '0')
        ciudad = request.GET.get('ciudad', '0')
        tienda = request.GET.get('tienda', '0')
        fecha = datetime.today() + timedelta(days=1)
        inicio = request.GET.get('inicio','%d/%d/%d'%(fecha.day,fecha.month,fecha.year))
        fin = request.GET.get('fin', '%d/%d/%d'%(fecha.day,fecha.month,fecha.year))
        busqueda = request.GET.get('busqueda', '')
        cursor = connection.cursor()
        m = ' SET datestyle = dmy;select reporte_general(\'{%s}\'::text,\'%s\'::date,\'%s\'::date);' % (
            empleados, inicio, fin)
        cursor.execute(m)
        row = cursor.fetchone()
        print row[0]
        context = self.get_context_data(**kwargs)
        context.update({'inicio':inicio})
        context.update({'fin':fin})
        context.update({'empleados':row[0]})
        print context
        return self.render_to_response(context)
    # end def
# end


class EmpleadoEspicificoImprimir(PDFTemplateView):
    template_name = "reporte/pagoespeficico.html"

    def get(self, request, *args, **kwargs):
        empleados=','.join( x for x in map(str, request.GET.getlist('reporte','')))
        fecha = datetime.today() + timedelta(days=1)
        inicio = request.GET.get('inicio','%d/%d/%d'%(fecha.day,fecha.month,fecha.year))
        fin = request.GET.get('fin', '%d/%d/%d'%(fecha.day,fecha.month,fecha.year))
        busqueda = request.GET.get('busqueda', '')
        cursor = connection.cursor()
        m = 'SET datestyle = "ISO, DMY";select reporte_especifico(\'{%s}\'::text,\'%s\'::date,\'%s\'::date)' % (
            empleados, inicio, fin)
        cursor.execute(m)
        row = cursor.fetchone()
        for x in row[0][0]['data_']:
            print x
        #end for
        context = self.get_context_data(**kwargs)
        context.update({'inicio':inicio})
        context.update({'fin':fin})
        context.update({'empleados':row[0][0]['data_'] if row[0][0]['data_'] else []})
        context.update({'info':row[0][0]['info'][0] if row[0][0]['info'] else []})
        context.update({'total':row[0][0]['ttotal'] if row[0][0]['info'] else []})
        return self.render_to_response(context)
    # end def
# end class

reporte/templates/reporte/pagoespeficico.html
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Reporte General</title>
  <style>
table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    padding: 8px;
    text-align: left;
    border-bottom: 1px solid #ddd;
}

tr:hover{background-color:#f5f5f5}
</style>

</head>
<body>
  <h1>Reporte de pago entre <span>{{ inicio }}</span> y <span>{{ fin }}</span></h1>
    {% if info %}
    <h1>
      <ul>
        <li><label for="">Empresa : </label> <span>{{ info.empresa}}</span></li>
        <li><label for="">Tienda : </label> <span>{{ info.tienda}}</span></li>
        <li><label for="">Ciudad : </label> <span>{{ info.ciudad}}</span></li>
        <li><label for="">Identificacion : </label> <span>{{ info.identificacion}}</span></li>
        <li><label for="">Nombre : </label> <span>{{ info.nombre}} {{ info.apellidos }}</span></li>
        <li><label for="">Celular : </label> <span>{{ info.celular }}</span></li>
        <li><label for="">Direccion : </label> <span>{{ info.direccion}} </span></li>
      </ul>
    </h1>

    {% endif %}
    {% if empleados %}
      <table>
        <thead>
          <tr>
            <th>Inicio</th>
            <th>Fin</th>
            <th>Horas</th>
            <th>Total</th>
          </tr>
        </thead>
        <tbody>
          {% for o in empleados %}
            <tr>
              <td>{{ o.ini }}</td>
              <td>{{ o.fin }}</td>
              <td>{{ o.horas }}</td>
              <td>{{ o.total_horas }}</td>
            </tr>
          {% endfor %}
          <tr>
            <td>  </td>
            <td>  </td>
            <td>TOTAL</td>
            <td>{{ total }}</td>
          </tr>
        </tbody>
      </table>
    {% else %}
      No Existe la empleados para informe.
    {% endif %}
</body>
</html>

reporte/templates/reporte/pagos.html
{% extends 'Registered/base2.html' %}
{% load staticfiles %}
{% block title %}Listar empleados{% endblock %}
{% block javascript %}
  <!--script type="text/javascript" src="http://malsup.github.com/jquery.form.js"></script-->
  <script type="text/javascript" src="{% static 'Registered/js/jqueryform.js' %}"></script>
  <!--script type="text/javascript" src="{% static 'Registered/js/valid_form_ajax.js' %}"></script>
  <script type="text/javascript" src="{% static 'usuario/js/editempleado.js' %}"></script-->
  <script type="text/javascript" src="{% static 'reporte/js/reportes.js' %}"></script>
  <!--script type="text/javascript" src="{% static 'usuario/js/addempleado.js' %}"></script>
  <script type="text/javascript" src="{% static 'usuario/js/deleteempleado.js' %}"></script-->
{% endblock %}
{% block css %}
  <!--link rel="stylesheet" href="{% static 'usuario/css/empleado.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'operacion/css/listar_labores.css' %}"-->
{% endblock %}
{% block tool %}
<div class="row cajaIn caja">
  <div class="col s4 m4 l4 ">
    <select id = "empresa" {% if not empresa %} disabled{% endif %}>
      <option value="0" disabled selected>{% if empresa %}Empresa{% else %} No Registros {% endif %}</option>
      {% if empresa %}
      {% for c in empresa %}
      <option value="{{ c.id }}">{{ c.first_name }}</option>
      {% endfor %}
      {% endif %}
    </select>
    <label>Empresa</label>
  </div>
  <div class="col s4 m4 l4 ">
    <select id="ciudad" disabled>
      <option value="" disabled selected>Ciudad</option>
      <option value="1">Option 1</option>
      <option value="2">Option 2</option>
      <option value="3">Option 3</option>
    </select>
    <label>Ciudad</label>
  </div>
  <div class="col s4 m4 l4 ">
    <select id="tienda" disabled>
      <option value="" disabled selected>Tienda</option>
      <option value="1">Option 1</option>
      <option value="2">Option 2</option>
      <option value="3">Option 3</option>
    </select>
    <label>Tienda</label>
  </div>
</div>

<div class="row cajaIn caja">
  <div class="col s3 m3 l3 ">
      <input type="date" class="datepicker" placeholder="Fecha Inicio" id="inicio">
  </div>
  <div class="col s3 m3 l3 ">
     <input type="date" class="datepicker" placeholder="Fecha Fin" id="fin">
  </div>
  <div class="col s4 m4 l4 ">
     <input placeholder="Busqueda" id="search" type="text" class="validate">
  </div>
  <div class="col s1 m1 l1 ">
     <a href="{% url 'usuario:add_empleado' %}"class="btn-floating btn-large waves-effect waves-light #4db6ac cons_emp"><i class="material-icons" id="addtrabajador">search</i></a>
  </div>
</div>
{% endblock %}
{% block contenido %}
<div class="row cajaIn caja">
  <div class="col s12 m12 l12" id="Tabla">
    <form action="" id="envio">
          <table class="highlight centered">
            <thead>
              <tr>
                <th><span class=""><input type="checkbox" id="test5" class="all_empleados"/>
            <label for="test5"></label></span></th>
                <th>Empresa</th>
                <th>Ciudad</th>
                <th>Tienda</th>
                <th>Identificacion</th>
                <th>Nombre</th>
                <th>Apellidos</th>
                <th>Numero de Horas</th>
                <th>Total</th>
                <th><a href="#" class="reporte_general"><img src="{{ MEDIA_URL }}des2.png" /></a></th>
                </th>
              </tr>
            </thead>
            <tbody id="tab_emp">

            </tbody>
          </table>
        </form>
  </div>
</div>
{% endblock %}
{% block dialog %}
<div id="info" class="modal">
    <div class="modal-content">
      <h4>Consultar Pagos</h4>
      <p id="con_info"></p>
    </div>
    <div class="modal-footer">
      <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Ok</a>
    </div>
</div>
<div id="addempleado" class="modal modal-fixed-footer">
  <div class="modal-content">
    <h4>Registrar Trabajador</h4>
    <div id="contenido">

    </div>
  </div>
  <div class="modal-footer">
    <a href="#!" class="modal-action waves-effect waves-green btn-flat saveempleado">Guardar</a>
    <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Cancelar</a>
  </div>
</div>
<div id="editempleado" class="modal modal-fixed-footer">
  <div class="modal-content">
    <h4>Editar Trabajador</h4>
    <div id="edit_contenido">

    </div>
  </div>
  <div class="modal-footer">
    <a href="#!" class="modal-action waves-effect waves-green btn-flat edit_modal_empleado">Modificar</a>
    <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Cancelar</a>
  </div>
</div>
<div id="deleteempleado" class="modal modal-fixed-footer">
  <div class="modal-content">
    <h4>Eliminar Trabajador</h4>
    <div id="cont_delete_mod">

    </div>
  </div>
  <div class="modal-footer">
    <a href="#!" class="modal-action waves-effect waves-green btn-flat delete_save_empleado">Si</a>
    <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">No</a>
  </div>
</div>
{% endblock %}

reporte/templates/reporte/pagosgeneral.html
{% load humanize %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Reporte General</title>
  <style>
table {
    border-collapse: collapse;
    width: 100%;
}

th, td {
    padding: 8px;
    text-align: left;
    border-bottom: 1px solid #ddd;
}

tr:hover{background-color:#f5f5f5}
</style>

</head>
<body>
  <h1>Reporte de pago entre <span>{{ inicio }}</span> y <span>{{ fin }}</span></h1>
    {% if empleados %}
      <table>
        <thead>
          <tr>
            <th>Empresa</th>
            <th>Tienda</th>
            <th>Identificacion</th>
            <th>Nombre</th>
            <th>Apellidos</th>
            <th>Horas</th>
            <th>Total</th>
          </tr>
        </thead>
        <tbody>
          {% for o in empleados %}
            <tr>
              <td>{{ o.nom_empre }}</td>
              <td>{{ o.nom_tienda }}</td>
              <td>{{ o.identificacion }}</td>
              <td>{{ o.nom_emp }}</td>
              <td>{{ o.ape_emp }}</td>
              <td>{{ o.total_turnos }}</td>
              <td>{{ o.total_horas }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      No Existe la empleados para informe.
    {% endif %}
</body>
</html>

reporte/templates/reporte/reportes.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'Registered/css/home.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
      <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/js/materialize.min.js"></script>
	<title>Reportes</title>
  <style type="text/css">
  </style>
</head>
<body>

<header>
			<div class="row">
				<div class="col s6 m4 l2 offset-s1 offset-m1 offset-l1">
					<div class="row">
						<a href="{% url 'index' %}">
						<div class="col s3 m3 l3">
							<center><i class="material-icons" id="logeoT">phonelink_lock</i></center>
						</div>
						<div class="col s6 m6 l6">
							<center><p id="titulo">Registered</p></center>
						</div>
						</a>
					</div>
			    </div>
			  	<div class="col s2 m4 l7 "></div>
			  	<div class="col s3 m2 l1">
			    	<center><a href="{% url 'usuario:logout' %}"><i class="material-icons" id="close">input</i></a></center>
			  	</div>
			</div>
		</header>

<section>
	<div class="container">
		<div class="row">

			<div class="col s12 m6 l3" id="Carta">
				<div class="card">
		            <div class="card-image">
		              <center><a href="{% url 'reporte:pagos' %}"><i class="material-icons" id="logeo">&#xE85D;</i></a></center>
		            </div>
		            <div class="card-content">
		              <center><p>Total a pagar</p></center>
		            </div>
	          	</div>
			</div>

      <div class="col s12 m6 l3" id="Carta">
				<div class="card">
		            <div class="card-image">
		              <center><a href=""><i class="material-icons" id="logeo">&#xE85D;</i></a></center>
		            </div>
		            <div class="card-content">
		              <center><p>Total a pagar detallado</p></center>
		            </div>
	          	</div>
			</div>

		</div>
	</div>
</section>

</body>
</html>