Registered/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
import settings
from django.conf.urls.static import static
import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^nested_admin/', include('nested_admin.urls')),
    url(r'^operacion/', include('operacion.urls',namespace='operacion')),
    url(r'^usuario/', include('usuario.urls',namespace='usuario')),
    url(r'^empresa/', include('empresa.urls',namespace='empresa')),
    url(r'^motorizado/', include('motorizado.urls',namespace='motorizado')),
    url(r'^reporte/', include('reporte.urls',namespace='reporte')),
    url(r'^$', login_required(views.Index.as_view()),name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empresa/urls.py
from django.conf.urls import url
import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required


#Manejo de empresa
urlpatterns = [
    url(r'list/empresa/$', login_required(views.ListEmpresa.as_view()), name='list_empresa'),
    url(r'add/empresa/$', login_required(views.AddEmpresa.as_view()), name='add_empresa'),
    url(r'edit/empresa/(?P<pk>\d+)/$', login_required(views.EditEmpresa.as_view()), name='edit_empresa'),
    url(r'change/pass/empresa/$', login_required(views.SetPassWordEmpresa.as_view()), name='change_pass_empresa'),
    url(r'delete/empresa/(?P<pk>\d+)/$', login_required(views.DeleteEmpresa.as_view()), name='delete_pass_empresa'),
]

#Manejo de tienda
urlpatterns += [
    url(r'list/tienda/$', login_required(views.ListTienda.as_view()), name='list_tienda'),
    url(r'add/tienda/$', login_required(views.AddTienda.as_view()), name='add_tienda'),
    url(r'edit/tienda/(?P<pk>\d+)/$', login_required(views.AddTienda.as_view()), name='edit_tienda'),
    url(r'delete/tienda/(?P<pk>\d+)/$', login_required(views.DeleteTienda.as_view()), name='delete_pass_tienda'),
]

#Manejo de tienda
urlpatterns += [
    url(r'list/supervisor/$', login_required(views.ListSupervisor.as_view()), name='list_supervisor'),
    url(r'add/supervisor/$', login_required(views.AddSupervisor.as_view()), name='add_supervisor'),
    url(r'edit/supervisor/(?P<pk>\d+)/$', login_required(views.EditSupervisor.as_view()), name='edit_supervisor'),
    url(r'delete/supervisor/(?P<pk>\d+)/$', login_required(views.DeleteSupervisor.as_view()), name='delete_pass_supervisor'),
]

#Manejo de ciudad
urlpatterns += [
    url(r'list/ciudad/$', login_required(views.ListCiudad.as_view()), name='list_ciudad'),
]

#vista
urlpatterns += [
    url(r'indexEmpresas/$',login_required(views.Empresas.as_view()), name='index_empresas'),
]

#vista Tiendas
urlpatterns += [
    url(r'indexTienda/$',login_required(views.Tiendas.as_view()), name='index_tiendas'),
]

#vista Supervisores
urlpatterns += [
    url(r'indexsupervisor/$',login_required(views.Supervisores.as_view()), name='index_supervisor'),
]

motorizado/urls.py
from django.conf.urls import url
import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
#Inicio de session
urlpatterns = [
    url(r'^motos/$',login_required(TemplateView.as_view(template_name='motorizado/motos.html')), name='infomoto'),
    url(r'^add/moto/$',login_required(views.AddMoto.as_view()) ,name='add_moto'),
    url(r'^edit/moto/(?P<pk>\d+)/$',login_required(views.AddMoto.as_view()) ,name='edit_moto'),
    url(r'^delete/moto/(?P<pk>\d+)/$',login_required(views.DeleteMoto.as_view()) ,name='delete_moto'),
    url(r'^list/moto/',login_required(views.ListMoto.as_view()) ,name='lis_moto'),
    url(r'^list/motorizado/',login_required(views.ListMotorizados.as_view()) ,name='lis_motorizado'),
]

operacion/urls.py
from django.conf.urls import url
import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

'''urlpatterns = [
    url(r'login/$', views.custom_login, {'template_name': 'usuario/login.html'}, name='user-login'),
    url(r'logout/$', views.custom_logout, {'next_page': '/', }, name='user-logout'),
]'''

#formularios configuracion
urlpatterns = [
    url(r'^configuraciones/$',login_required(TemplateView.as_view(template_name='operacion/configuraciones.html')), name='configuraciones'),
    url(r'add/configuracion/$',login_required(views.AddConfiguracionWS.as_view()) ,name='add_conf'),
    url(r'edit/configuracion/(?P<pk>\d)/$',login_required(views.AddConfiguracion.as_view()) ,name='edit_conf'),
    url(r'list/configuracion/$',login_required(views.ListConfiguracion.as_view()) ,name='list_conf'),
]


#formularios configuracion
urlpatterns += [
    url(r'add/labor/$',login_required(views.AddLabor.as_view()) ,name='add_labor'),
    url(r'edit/labor/',login_required(views.EditLabor.as_view()) ,name='edit_labor'),
    url(r'delete/labor/(?P<pk>\d)/$',login_required(views.DeleteLabor.as_view()) ,name='delete_labor'),
    url(r'list/labor/$',login_required(views.ListLabor.as_view()) ,name='list_labor'),
]

#funcionalidad de adicional labor
urlpatterns += [
    url(r'labores/$',views.Labores.as_view() ,name='labores'),
    url(r'movil/trabajos/$',login_required(views.MobilLabore.as_view()) ,name='movil_labores'),
    url(r'ws/labor/$',login_required(views.AddWsLabor.as_view()) ,name='ws_labor'),
]

#funciones de la funcion de Observaciones
urlpatterns += [
    url(r'index/observacion/$',login_required(TemplateView.as_view(template_name='operacion/observaciones.html')),name='index_observacion'),
    url(r'add/observacion/$',login_required(views.AddObservacion.as_view()),name='add_observacion'),
    url(r'edit/observacion/(?P<pk>)/$',login_required(views.AddObservacion.as_view()),name='edit_observacion'),
    url(r'delete/observacion/(?P<pk>)/$',login_required(views.DeleteObservacion.as_view()),name='delete_observacion'),
    url(r'list/observacion/$',login_required(views.ListObservacion.as_view()),name='list_observacion'),
    url(r'validar/observacion/(?P<pk>)/$',login_required(views.ValidarObservacion.as_view()),name='valid_observacion'),
]

reporte/urls.py
from django.conf.urls import url
import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
#Inicio de session
urlpatterns = [
    url(r'^pagos/$',login_required(views.Pagos.as_view()), name='pagos'),
    url(r'^home/pagos/$',login_required(views.Reporte.as_view()), name='reportes'),
]

#
urlpatterns += [
    url(r'^ws/pagos/empledos/$',login_required(views.WsPagosEmpleados.as_view()), name='ws_pagos'),
]


#reporte depagos
urlpatterns += [
    url(r'^ws/pagos/empledos/imprimir/$',login_required(views.WsPagosEmpleadosImprimir.as_view()), name='ws_pagosg'),
]

#reporte depagos
urlpatterns += [
    url(r'^pagos/empledo/especifico/imprimir/$',login_required(views.EmpleadoEspicificoImprimir.as_view()), name='ws_pagose'),
]

usuario/urls.py
from django.conf.urls import url
import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

#empleado
urlpatterns = [
    url(r'^login/empleado/$',login_required(views.LoginEmpleado.as_view()) ,name='login_empleado'),
    url(r'^add/empleado/$',login_required(views.AddEmpleado.as_view()) ,name='add_empleado'),
    url(r'^edit/empleado/(?P<pk>\d+)/$',login_required(views.EditEmpleado.as_view()) ,name='edit_empleado'),
    url(r'^delete/empleado/(?P<pk>\d+)/$',login_required(views.DeleteEmpleado.as_view()) ,name='delete_empleado'),
    url(r'^list/empleado/',login_required(views.ListEmpleado.as_view()) ,name='lis_empleado'),
    url(r'^list/empleados/',login_required(views.ListEmpleados.as_view()) ,name='list_empleados'),
    url(r'^change/pass/empleados/',login_required(views.SetPassWordEmpleado.as_view()) ,name='set_pass_empleado'),
    url(r'^is/login/administrador/$',login_required(views.IsLogin.as_view()) ,name='is_login_admin'),
]


#direccionamientos del empleado a nivel de vista
urlpatterns += [
    url(r'^view/empleados/$',login_required(views.GeneralCliente.as_view()), name='view_empleados'),
]


#Inicio de session
urlpatterns += [
    url(r'^login/$',views.Login.as_view(), name='login'),
    url(r'^logout/$',views.Logout.as_view(), name='logout'),
]


# manejo de usuario de empleados escritorio
urlpatterns += [
    url(r'^empleados/$',login_required(views.Empleados.as_view()), name='esc_lis_empleados'),
]


# registro de supervisores
urlpatterns += [
    url(r'^supervisores/$',login_required(views.Supervisores.as_view()), name='supervisoress'),
]

Registered/views.py
# -*- coding: utf-8 -*-
from django.views.generic import TemplateView
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
import decorators
from django.utils.decorators import method_decorator

class Index(TemplateView):

    @method_decorator([login_required, decorators.user_supervisor])
    def dispatch(self, request, *args, **kwargs):
        return render(request, 'Registered/home.html')
    # end def
# end class

Registered/templates/Registered/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <script type="text/javascript" src="{% static 'Registered/js/jquery-2.1.1.min.js' %}"></script>
  <link rel="stylesheet" href="{% static 'Registered/css/materialize.min.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="{% static 'Registered/js/materialize.min.js' %}"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
  <!--link href="{% static 'Registered/css/estilo.css' %}" rel="stylesheet">
  <link href="{% static 'Registered/css/home.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'usuario/css/listarempleado.css' %}"-->
  <link rel="stylesheet" href="{% static 'Registered/css/base.css' %}">  
  {% block javascript %}{% endblock %}
  {% block css %}{% endblock %}
  <script src="{% static 'Registered/js/scri.js' %}"></script>
  <meta charset="UTF-8">
  <title>{% block title%} {% endblock %}</title>
</head>
 <body>

   <header>
      <div class="row">
        <div class="col s6 m4 l2 offset-s1 offset-m1 offset-l1">
          <div class="row">
            <a href="{% url 'index' %}">
            <div class="col s3 m3 l3">
              <center><i class="material-icons" id="logeoT">phonelink_lock</i></center>
            </div>
            <div class="col s6 m6 l6">
              <center><p id="titulo">Registered</p></center>
            </div>
            </a>
          </div>
          </div>
          <div class="col s2 m4 l7 "></div>
          <div class="col s3 m2 l1">
            <center><a href="{% url 'usuario:logout' %}"><i class="material-icons" id="close">input</i></a></center>
          </div>
      </div>
    </header>

   <div class="container filtro">
     {% block tool %}
     
     {% endblock %}
   </div>

   <section>
     <div class="container">
       {% block contenido %}

       {% endblock %}
    </div>
  </section>
{% block dialog %}
{% endblock %}
 </body>
</html>

Registered/templates/Registered/base2.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <script type="text/javascript" src="{% static 'Registered/js/jquery-2.1.1.min.js' %}"></script>
  <link rel="stylesheet" href="{% static 'Registered/css/materialize.min.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="{% static 'Registered/js/materialize.min.js' %}"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
  <!--link href="{% static 'Registered/css/estilo.css' %}" rel="stylesheet">
  <link href="{% static 'Registered/css/home.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'usuario/css/listarempleado.css' %}"-->
  <link rel="stylesheet" href="{% static 'Registered/css/base2.css' %}">
  {% block javascript %}{% endblock %}
  {% block css %}{% endblock %}
  <script src="{% static 'Registered/js/scri.js' %}"></script>
  <meta charset="UTF-8">
  <title>{% block title%} {% endblock %}</title>
</head>
 <body>

   <header>
      <div class="row">
        <div class="col s6 m4 l2 offset-s1 offset-m1 offset-l1">
          <div class="row">
            <a href="{% url 'index' %}">
            <div class="col s3 m3 l3">
              <center><i class="material-icons" id="logeoT">phonelink_lock</i></center>
            </div>
            <div class="col s6 m6 l6">
              <center><p id="titulo">Registered</p></center>
            </div>
            </a>
          </div>
          </div>
          <div class="col s2 m4 l7 "></div>
          <div class="col s3 m2 l1">
            <center><a href="{% url 'usuario:logout' %}"><i class="material-icons" id="close">input</i></a></center>
          </div>
      </div>
    </header>

   <div class="container filtro">
     {% block tool %}

     {% endblock %}
   </div>

   <section>
     <div class="container">
       {% block contenido %}

       {% endblock %}
    </div>
  </section>
{% block dialog %}
{% endblock %}
 </body>
</html>

Registered/templates/Registered/home.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
	    <meta http-equiv="X-UA-Compatible" content="ie=edge">
	    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
	    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/css/materialize.min.css">
	    <link rel="stylesheet" type="text/css" href="{% static 'Registered/css/home.css' %}">
	    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
	    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
	      rel="stylesheet">
	    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/js/materialize.min.js"></script>
		<title>Home - Registered</title>
	  <style type="text/css">
	  </style>
	</head>
	<body>
		<header>
			<div class="row">
				<div class="col s6 m4 l2 offset-s1 offset-m1 offset-l1">
					<div class="row">
						<a href="{% url 'index' %}">
						<div class="col s3 m3 l3">
							<center><i class="material-icons" id="logeoT">phonelink_lock</i></center>
						</div>
						<div class="col s6 m6 l6">
							<center><p id="titulo">Registered</p></center>
						</div>
						</a>
					</div>
			    </div>
			  	<div class="col s2 m4 l7 "></div>
			  	<div class="col s3 m2 l1">
			    	<center><a href="{% url 'usuario:logout' %}"><i class="material-icons" id="close">input</i></a></center>
			  	</div>
			</div>
		</header>

		<section>
			<div class="container">
				<div class="row">


					<a href="{% url 'empresa:index_empresas' %}">
					<div class="col s12 m6 l3" id="Carta">
						<div class="card">
				            <div class="card-image">
				              <center><i class="material-icons" id="logeo">&#xE8D1;</i></center>
				            </div>
				            <div class="card-content">
				              <center><p>Empresas</p></center>
				            </div>
			          	</div>
					</div>
					</a>

					<a href="{% url "reporte:reportes" %}">
					<div class="col s12 m6 l3" id="Carta">
						<div class="card">
				            <div class="card-image">
				              <center><i class="material-icons" id="logeo">&#xE85D;</i></center>
				            </div>
				            <div class="card-content">
				              <center><p>Informes</p></center>
				            </div>
			          	</div>
					</div>
					</a>

					<a href="{% url 'usuario:esc_lis_empleados' %}">
					<div class="col s12 m6 l3" id="Carta">
						<div class="card">
				            <div class="card-image">
				              <center><i class="material-icons" id="logeo">&#xE7FB;</i></center>
				            </div>
				            <div class="card-content">
				              <center><p>Empleados</p></center>
				            </div>
			          	</div>
					</div>
					</a>

					<a href="{% url 'empresa:index_tiendas' %}">
					<div class="col s12 m6 l3" id="Carta">
						<div class="card">
				            <div class="card-image">
				              <center><i class="material-icons" id="logeo">&#xE8D1;</i></center>
				            </div>
				            <div class="card-content">
				              <center><p>Tienda</p></center>
				            </div>
			          	</div>
					</div>
					</a>

					<a href="">
					<div class="col s12 m6 l3" id="Carta">
						<div class="card">
				            <div class="card-image">
				              <center><i class="material-icons" id="logeo">supervisor_account</i></center>
				            </div>
				            <div class="card-content">
				              <center><p>Supervisor</p></center>
				            </div>
			          	</div>
					</div>
					</a>

					<a href="{% url 'operacion:configuraciones' %}">
					<div class="col s12 m6 l3" id="Carta">
						<div class="card">
				            <div class="card-image">
				              <center><i class="material-icons" id="logeo">&#xE227;</i></center>
				            </div>
				            <div class="card-content">
				              <center><p>Pago</p></center>
				            </div>
			          	</div>
					</div>
					</a>

					<a href="{% url 'motorizado:infomoto' %}">
					<div class="col s12 m6 l3" id="Carta">
						<div class="card">
				            <div class="card-image">
				              <center><i class="material-icons" id="logeo">&#xE91B;</i></center>
				            </div>
				            <div class="card-content">
				              <center><p>Motorizado</p></center>
				            </div>
			          	</div>
					</div>
					</a>

					<a href="{% url 'operacion:index_observacion' %}">
					<div class="col s12 m6 l3" id="Carta">
						<div class="card">
				            <div class="card-image">
				              <center><i class="material-icons" id="logeo">&#xE7FB;</i></center>
				            </div>
				            <div class="card-content">
				              <center><p>Observaciones</p></center>
				            </div>
			          	</div>
					</div>
					</a>

				</div>
			</div>
		</section>
	</body>
</html>

Registered/templates/Registered/login.html

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <link rel="stylesheet" href="login.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/js/materialize.min.js"></script>
  <title>Login</title>
</head>
<body>
  <section>

    <div class="container">

      <div class="row">

        <div class="col s10 push-s1">

            <div class="row">

                 <div class="col m5 hide-on-small-only"> 
                   <img class="logo" src="logo_express.svg" alt="no encontrado recurso"/>
                 </div> 

              <div class="col s12 m7">
                <h1 class="title">Register</h1>

                <form action="" class="signup-form">
                  <h2>Iniciar session</h2>

                  <div class="section">
                    <!--a href="" class="btn btn-fb hide-on-small-only">Iniciar sesiòn</a>
                    <a href="" class="btn btn-fb hide-on-med-and-up">Iniciar sesiòn</a-->
                  </div>

                  <div class="divider"></div>

                  <div class="section">
                    <input type="text" placeholder="Usuario">
                    <input type="password" name="password" placeholder="Contraseña">
                    <button class="btn btn-fb hide-on-small-only" type="submit">Iniciar sesiòn con facebook</a>
                    <button class="btn btn-fb hide-on-med-and-up" type="submit">Iniciar sesiòn</a>
                  </div>

                </form>
              </div>

              <div></div>
            </div>
        </div>
      </div>
     </div>
  </section>
  <footer class="site-footer">
    <div class="container">
      <div class="row">
        <div class="col s12 l3 push-l8 center-align">
          Express del Norte
        </div>
      </div>
    </div>

  </footer>
</body>
</html>

Registered/templates/Registered/loginEmp.html
<!DOCTYPE html>
<html lang="en">
<head>
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/js/materialize.min.js"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <script src="scri.js"></script>
	<meta charset="UTF-8">
	<title>login</title>
</head>
<body>
	<a class="waves-effect waves-light btn" href="#modal1">Modal</a>

  <!-- Modal Structure -->
  <div id="modal1" class="modal">
    <div class="modal-content">
      <h4>Modal Header</h4>
      <p>A bunch of text</p>
      <form action="" class="signup-form">
                  <h2>Iniciar session</h2>

                  <div class="section">
                    <!--a href="" class="btn btn-fb hide-on-small-only">Iniciar sesiòn</a>
                    <a href="" class="btn btn-fb hide-on-med-and-up">Iniciar sesiòn</a-->
                  </div>

                  <div class="divider"></div>

                  <div class="section">
                    <input type="text" placeholder="Usuario">
                    <input type="password" name="password" placeholder="Contraseña">
                    <button class="btn btn-fb hide-on-small-only" type="submit">Iniciar sesiòn con facebook</a>
                    <button class="btn btn-fb hide-on-med-and-up" type="submit">Iniciar sesiòn</a>
                  </div>

                </form>
    </div>
    <div class="modal-footer">
      <a href="#modal1" class="modal-action modal-close waves-effect waves-green btn-flat">Agree</a>
    </div>
  </div>
</body>
</html>

Registered/templates/Registered/principalLogin.html
<!DOCTYPE html>
<html lang="en">
<head>
  <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/css/materialize.min.css">
  <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/js/materialize.min.js"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <script src="scri.js"></script>
  <link rel="stylesheet" href="estilo.css">
  <meta charset="UTF-8">
  <title></title>
</head>
<body>

	<div class="row">
		<div class="col s12" id="header">
			<a href=""><i class="material-icons" id="house">home</i></a>
		</div>
	</div>
<div class="row">
  <div class="col s9 m9 tool offset-s1 offset-m1" id="tool">
    <div class="card horizontal">
      <div class="card-stacked">
        <div class="card-content">
          <div class="row">
          <div class="input-field col s4 m4">
            <select>
              <option value="" disabled selected>Choose your option</option>
              <option value="1">Option 1</option>
              <option value="2">Option 2</option>
              <option value="3">Option 3</option>
            </select>
            <label>Materialize Select</label>
          </div>
          <div class="input-field col s4 m4">
            <select>
              <option value="" disabled selected>Choose your option</option>
              <option value="1">Option 1</option>
              <option value="2">Option 2</option>
              <option value="3">Option 3</option>
            </select>
            <label>Materialize Select</label>
          </div>
          <div class="input-field col s4 m4">
            <select>
              <option value="" disabled selected>Choose your option</option>
              <option value="1">Option 1</option>
              <option value="2">Option 2</option>
              <option value="3">Option 3</option>
            </select>
            <label>Materialize Select</label>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
	<div class="row">
		<div class="col s1"></div>
		<div class="col s10" id="main">
			<table class="highlight responsive-table">
		        <thead>
		          <tr>
		              <th>Empresa</th>
		              <th>Ciudad</th>
		              <th>Tienda</th>
		              <th>Nombre Trabajador</th>
		              <th>Hora Entrada</th>
		              <th>opciones</th>
		          </tr>
		        </thead>

		        <tbody>
		          <tr>
		            <td>Alvin</td>
		            <td>Eclair</td>
		            <td>$0.87</td>
		            <td>Alvin</td>
		            <td>Eclair</td>
		            <td>$0.87</td>
		          </tr>
		          <tr>
		            <td>Alan</td>
		            <td>Jellybean</td>
		            <td>$3.76</td>
		            <td>Alvin</td>
		            <td>Eclair</td>
		            <td>$0.87</td>
		          </tr>
		          <tr>
		            <td>Jonathan</td>
		            <td>Lollipop</td>
		            <td>$7.00</td>
		            <td>Alvin</td>
		            <td>Eclair</td>
		            <td>$0.87</td>
		          </tr>
		          <tr>
		            <td>Jonathan</td>
		            <td>Lollipop</td>
		            <td>$7.00</td>
		            <td>Alvin</td>
		            <td>Eclair</td>
		            <td>$0.87</td>
		          </tr>
		          <tr>
		            <td>Jonathan</td>
		            <td>Lollipop</td>
		            <td>$7.00</td>
		            <td>Alvin</td>
		            <td>Eclair</td>
		            <td>$0.87</td>
		          </tr>
		          <tr>
		            <td>Jonathan</td>
		            <td>Lollipop</td>
		            <td>$7.00</td>
		            <td>Alvin</td>
		            <td>Eclair</td>
		            <td>$0.87</td>
		          </tr>
		        </tbody>
            </table>
		</div>
		<div class="col s1" id="add">
			  <a class="btn-floating btn-large waves-effect waves-light orange darken-3 " href="#modal1"><i class="material-icons ">add</i></a>
		</div>
	</div>
	<div class="row">
		<div class="col s12" id="menu">
			<ul class="pagination">
			    <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
			    <li class="active"><a href="#!">1</a></li>
			    <li class="waves-effect"><a href="#!">2</a></li>
			    <li class="waves-effect"><a href="#!">3</a></li>
			    <li class="waves-effect"><a href="#!">4</a></li>
			    <li class="waves-effect"><a href="#!">5</a></li>
			    <li class="waves-effect"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
			</ul>
		</div>
	</div>

<div id="modal1" class="modal">
    <div class="modal-content">
      <form action="" class="signup-form">
	        <center><h2>Iniciar Sesión</h2></center>
	      	<div>
		      <div class="section col s4">
		        <input type="text" placeholder="Usuario">
		        <input type="password" name="password" placeholder="Contraseña">
		        <center><button class="btn btn-fb " type="submit">Iniciar sesión</a></center>
		      </div>
			</div>
       </form>
    </div>
  </div>

</body>
</html>