Registered/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
import settings
from django.conf.urls.static import static
import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^nested_admin/', include('nested_admin.urls')),
    url(r'^operacion/', include('operacion.urls',namespace='operacion')),
    url(r'^usuario/', include('usuario.urls',namespace='usuario')),
    url(r'^empresa/', include('empresa.urls',namespace='empresa')),
    url(r'^motorizado/', include('motorizado.urls',namespace='motorizado')),
    url(r'^reporte/', include('reporte.urls',namespace='reporte')),
    url(r'^$', login_required(views.Index.as_view()),name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empresa/urls.py
from django.conf.urls import url
import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required


#Manejo de empresa
urlpatterns = [
    url(r'list/empresa/$', login_required(views.ListEmpresa.as_view()), name='list_empresa'),
    url(r'add/empresa/$', login_required(views.AddEmpresa.as_view()), name='add_empresa'),
    url(r'edit/empresa/(?P<pk>\d+)/$', login_required(views.EditEmpresa.as_view()), name='edit_empresa'),
    url(r'change/pass/empresa/$', login_required(views.SetPassWordEmpresa.as_view()), name='change_pass_empresa'),
    url(r'delete/empresa/(?P<pk>\d+)/$', login_required(views.DeleteEmpresa.as_view()), name='delete_pass_empresa'),
]

#Manejo de tienda
urlpatterns += [
    url(r'list/tienda/$', login_required(views.ListTienda.as_view()), name='list_tienda'),
    url(r'add/tienda/$', login_required(views.AddTienda.as_view()), name='add_tienda'),
    url(r'edit/tienda/(?P<pk>\d+)/$', login_required(views.AddTienda.as_view()), name='edit_tienda'),
    url(r'delete/tienda/(?P<pk>\d+)/$', login_required(views.DeleteTienda.as_view()), name='delete_pass_tienda'),
]

#Manejo de tienda
urlpatterns += [
    url(r'list/supervisor/$', login_required(views.ListSupervisor.as_view()), name='list_supervisor'),
    url(r'add/supervisor/$', login_required(views.AddSupervisor.as_view()), name='add_supervisor'),
    url(r'edit/supervisor/(?P<pk>\d+)/$', login_required(views.EditSupervisor.as_view()), name='edit_supervisor'),
    url(r'delete/supervisor/(?P<pk>\d+)/$', login_required(views.DeleteSupervisor.as_view()), name='delete_pass_supervisor'),
]

#Manejo de ciudad
urlpatterns += [
    url(r'list/ciudad/$', login_required(views.ListCiudad.as_view()), name='list_ciudad'),
]

#vista
urlpatterns += [
    url(r'indexEmpresas/$',login_required(views.Empresas.as_view()), name='index_empresas'),
]

#vista Tiendas
urlpatterns += [
    url(r'indexTienda/$',login_required(views.Tiendas.as_view()), name='index_tiendas'),
]

#vista Supervisores
urlpatterns += [
    url(r'indexsupervisor/$',login_required(views.Supervisores.as_view()), name='index_supervisor'),
]

operacion/urls.py
from django.conf.urls import url
import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

'''urlpatterns = [
    url(r'login/$', views.custom_login, {'template_name': 'usuario/login.html'}, name='user-login'),
    url(r'logout/$', views.custom_logout, {'next_page': '/', }, name='user-logout'),
]'''

#formularios configuracion
urlpatterns = [
    url(r'^configuraciones/$',login_required(TemplateView.as_view(template_name='operacion/configuraciones.html')), name='configuraciones'),
    url(r'add/configuracion/$',login_required(views.AddConfiguracionWS.as_view()) ,name='add_conf'),
    url(r'edit/configuracion/(?P<pk>\d)/$',login_required(views.AddConfiguracion.as_view()) ,name='edit_conf'),
    url(r'list/configuracion/$',login_required(views.ListConfiguracion.as_view()) ,name='list_conf'),
]


#formularios configuracion
urlpatterns += [
    url(r'add/labor/$',login_required(views.AddLabor.as_view()) ,name='add_labor'),
    url(r'edit/labor/',login_required(views.EditLabor.as_view()) ,name='edit_labor'),
    url(r'delete/labor/(?P<pk>\d)/$',login_required(views.DeleteLabor.as_view()) ,name='delete_labor'),
    url(r'list/labor/$',login_required(views.ListLabor.as_view()) ,name='list_labor'),
]

#funcionalidad de adicional labor
urlpatterns += [
    url(r'labores/$',views.Labores.as_view() ,name='labores'),
    url(r'movil/trabajos/$',login_required(views.MobilLabore.as_view()) ,name='movil_labores'),
    url(r'ws/labor/$',login_required(views.AddWsLabor.as_view()) ,name='ws_labor'),
]

#funciones de la funcion de Observaciones
urlpatterns += [
    url(r'index/observacion/$',login_required(TemplateView.as_view(template_name='operacion/observaciones.html')),name='index_observacion'),
    url(r'add/observacion/$',login_required(views.AddObservacion.as_view()),name='add_observacion'),
    url(r'edit/observacion/(?P<pk>)/$',login_required(views.AddObservacion.as_view()),name='edit_observacion'),
    url(r'delete/observacion/(?P<pk>)/$',login_required(views.DeleteObservacion.as_view()),name='delete_observacion'),
    url(r'list/observacion/$',login_required(views.ListObservacion.as_view()),name='list_observacion'),
    url(r'validar/observacion/(?P<pk>)/$',login_required(views.ValidarObservacion.as_view()),name='valid_observacion'),
]

usuario/urls.py
from django.conf.urls import url
import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

#empleado
urlpatterns = [
    url(r'^login/empleado/$',login_required(views.LoginEmpleado.as_view()) ,name='login_empleado'),
    url(r'^add/empleado/$',login_required(views.AddEmpleado.as_view()) ,name='add_empleado'),
    url(r'^edit/empleado/(?P<pk>\d+)/$',login_required(views.EditEmpleado.as_view()) ,name='edit_empleado'),
    url(r'^delete/empleado/(?P<pk>\d+)/$',login_required(views.DeleteEmpleado.as_view()) ,name='delete_empleado'),
    url(r'^list/empleado/',login_required(views.ListEmpleado.as_view()) ,name='lis_empleado'),
    url(r'^list/empleados/',login_required(views.ListEmpleados.as_view()) ,name='list_empleados'),
    url(r'^change/pass/empleados/',login_required(views.SetPassWordEmpleado.as_view()) ,name='set_pass_empleado'),
    url(r'^is/login/administrador/$',login_required(views.IsLogin.as_view()) ,name='is_login_admin'),
]


#direccionamientos del empleado a nivel de vista
urlpatterns += [
    url(r'^view/empleados/$',login_required(views.GeneralCliente.as_view()), name='view_empleados'),
]


#Inicio de session
urlpatterns += [
    url(r'^login/$',views.Login.as_view(), name='login'),
    url(r'^logout/$',views.Logout.as_view(), name='logout'),
]


# manejo de usuario de empleados escritorio
urlpatterns += [
    url(r'^empleados/$',login_required(views.Empleados.as_view()), name='esc_lis_empleados'),
]


# registro de supervisores
urlpatterns += [
    url(r'^supervisores/$',login_required(views.Supervisores.as_view()), name='supervisoress'),
]

usuario/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from supra import views as supra
import forms
import models
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views import generic
from django.views.generic.edit import UpdateView
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from cuser.middleware import CuserMiddleware
from django.views.generic import View, DeleteView
from django.contrib.auth import authenticate, login
from django.shortcuts import redirect, get_object_or_404, HttpResponse
from empresa import models as empresa
from operacion import models as operacion
from django.views.generic import TemplateView
from django.views.generic.edit import BaseFormView
from empresa import models as empresa
from django.contrib.auth.views import logout
from django.db.models import Q
from motorizado import forms as form_motorizado


class GeneralCliente(TemplateView):
    def dispatch(self, request, *args, **kwargs):
        user = CuserMiddleware.get_user()
        emp = empresa.Empresa.objects.filter(supervisor__id=user.id,active=True)
        return render(request, 'usuario/usuarios.html',{'empresa':emp})
    # end def
# end class


class Empleados(TemplateView):
    def dispatch(self, request, *args, **kwargs):
        user = CuserMiddleware.get_user()
        emp = empresa.Empresa.objects.filter(supervisor__id=user.id,active=True)
        return render(request, 'usuario/listarempleados.html',{'empresa':emp})
    # end def
# end class


class Supervisores(TemplateView):
    def dispatch(self, request, *args, **kwargs):
        user = CuserMiddleware.get_user()
        emp = empresa.Empresa.objects.filter(supervisor__id=user.id,active=True)
        return render(request, 'usuario/listarempleados.html',{'empresa':emp})
    # end def
# end class


class Logout(TemplateView):
    def dispatch(self, request, *args, **kwargs):
        logout(request)
        return redirect('usuario:login')
    # end def
# end class

# Create your views here.
class LoginEmpleado(View):
    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super(LoginEmpleado, self).dispatch(*args, **kwargs)
    # end def

    def post(self, request, *args, **kwargs):
        username = request.POST.get('user', False)
        passw = request.POST.get('pass', False)
        print 'Usuario---> ',username,'  ',passw
        if username and passw:
            print 'Usuario---> 1'
            user = authenticate(username=username, password=passw)
            if user is not None:
                print 'Usuario---> 2'
                return HttpResponse('[{"status":true,"id":%d}]'%(user.id), content_type='application/json', status=200)
            # end if
        # end if
        print 'Usuario---> 3'
        return HttpResponse('[{"status":false}]', content_type='application/json', status=202)
    # end def
# end class


class Login(BaseFormView):
    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super(Login, self).dispatch(*args, **kwargs)
    # end def

    def get(self, request, *args, **kwargs):
        return render(request,'usuario/login.html',{})
    #end def

    def post(self, request, *args, **kwargs):
        print request.POST
        username = request.POST.get('user', False)
        passw = request.POST.get('pass', False)
        if username and passw:
            print 'Usuario---> 1'
            user = authenticate(username=username, password=passw)
            if user is not None:
                print 'Usuario---> 2', user.id
                login(request, user)
                administrador = models.Administrador.objects.filter(id=user.id)
                if administrador:
                    print 'administrador---> 2'
                    return redirect('operacion:movil_labores')
                #end if
                supervisor = empresa.Supervisor.objects.filter(id=user.id)
                if supervisor:
                    print 'Suervisor---> 3'
                    return redirect('/')
                #end if
                if user.is_superuser :
                    print 'Admin---> 3'
                    return redirect('/admin')
                #end if
                return redirect('usuario:login')
            # end if
        # end if
        print 'Usuario---> 3'
        return redirect('usuario:login')
    # end def
# end class


class AddEmpleado(supra.SupraFormView):
    model = models.Empleado
    form_class = forms.EmpleadoForm
    template_name = 'usuario/addempleado.html'

    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super(AddEmpleado, self).dispatch(*args, **kwargs)
    # end def
# end class


class ListEmpleado(supra.SupraListView):
    model = models.Empleado
    search_key = 'q'
    list_display = ['id','identificacion','telefono_fijo','telefono_celular','first_name','last_name','direccion','documento','foto','fecha_nacimiento','documento','tienda']
    search_fields = ['id']
    paginate_by = 10

    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super(ListEmpleado, self).dispatch(*args, **kwargs)
    # end def
# end class


class ListEmpleados(supra.SupraListView):
    model = models.Empleado
    search_key = 'q'
    list_display = ['id','identificacion','telefono_fijo','telefono_celular','first_name','last_name','direccion','documento','foto','fecha_nacimiento','servicios','tienda_e','empresa_e','ciudad_e']
    search_fields = ['id']
    paginate_by = 100

    class Renderer:
        empresa_e ='tienda__empresa__first_name'
        ciudad_e = 'tienda__ciudad__nombre'
        tienda_e = 'tienda__nombre'
    #end class

    def servicios(self, obj, row):
        edit = "/usuario/edit/empleado/%d/" % (obj.id)
        delete = "/usuario/delete/empleado/%d/" % (obj.id)
        password = "change/pass/empleados/"
        return {'edit': edit, 'delete': delete,'pass':password}
    # end def

    def get_queryset(self):
        user = CuserMiddleware.get_user()
        emp = empresa.Empresa.objects.filter(supervisor__id=user.id).values_list('id', flat=True)
        print emp
        if self.request.GET.get('pagina', False):
            self.paginate_by = self.request.GET.get('pagina', False)
        #end if
        empr = self.request.GET.get('empresa', False)
        ciud = self.request.GET.get('ciudad', False)
        tiend = self.request.GET.get('tienda', False)
        busqueda = self.request.GET.get('search','')
        print 'Empresa ',empr,'  ciudad ',ciud,' tienda',tiend
        empleado = models.Empleado.objects.filter((Q(first_name__contains=busqueda) | Q(last_name__contains=busqueda) | Q(identificacion__contains=busqueda)) & Q(tienda__empresa__id__in=emp,estado=True))
        if empr and ciud and tiend:
            return empleado.filter(tienda__id=int(tiend), tienda__empresa__id=int(empr),tienda__ciudad__id=int(ciud))
        elif empr and ciud:
            print '****************'
            return empleado.filter(tienda__empresa__id=int(empr),tienda__ciudad__id=int(ciud))
        elif empr:
            return empleado.filter(tienda__empresa__id=int(empr))
        #end if
        return empleado

    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super(ListEmpleados, self).dispatch(*args, **kwargs)
    # end def
# end class


class EditEmpleado(supra.SupraFormView):
    model = models.Empleado
    form_class = forms.EmpleadoEditForm
    template_name = 'usuario/addempleado.html'

    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super(EditEmpleado, self).dispatch(*args, **kwargs)
    # end def
# end class


class DeleteEmpleado(View):
    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super(DeleteEmpleado, self).dispatch(*args, **kwargs)
    # end def

    def get(self, request, *args, **kwargs):
        print request,kwargs
        empr=kwargs['pk']
        if empr:
            print 1
            empre = models.Empleado.objects.filter(id=empr).first()
            if empre:
                print 2
                empre.estado=False
                empre.save()
                return HttpResponse('[{"status":true}]', content_type='application/json', status=200)
            # end if
        # end if
        print 3
        return HttpResponse('[{"status":false}]', content_type='application/json', status=202)
    # end def
# end class


class SetPassWordEmpleado(View):

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(SetPassWordEmpleado, self).dispatch(request, *args, **kwargs)
    # end def

    def get(self, request, *args, **kwargs):# 359291054481645
        passw = request.GET.get('password',False)
        iden = request.GET.get('identificador',False)
        if passwo and iden :
            emp = models.Empleado.objects.filter(id=request.GET.get('identificador','0')).first()
            if emp :
                    emp.set_password(raw_password=password)
                    emp.save()
                    return HttpResponse('{"r":"Ok"}', content_type="application/json", status=200)
            # end if
            return HttpResponse('{"r":"Campos invalidos"}', content_type="application/json", status=400)
        # end if
        return HttpResponse('{"r":"Campos requeridos"}', content_type="application/json", status=400)
    # end def
#end class


class IsLogin(View):
    @method_decorator(csrf_exempt)
    def dispatch(self, *args, **kwargs):
        return super(IsLogin, self).dispatch(*args, **kwargs)
    # end def

    def post(self, request, *args, **kwargs):
        username = request.user.username

usuario/templates/usuario/addempleado.html
<style>
ul  {
    list-style: None;
}
</style>
<form action="{% url 'usuario:add_empleado' %}" method="post" id="modal_add_empleado">
  {% csrf_token %}
  <ul>
    {{form.as_ul}}
  </ul>
</form>

usuario/templates/usuario/empleados_tienda.html
{% extends "Registered/base.html" %}
{% load staticfiles %}
{% block javascript %}
  <script type="text/javascript" src="{% static 'operacion/js/labores.js' %}"></script>
{% endblock %}
{% block css %}
  <!--link rel="stylesheet" href="{% static 'usuario/css/empleado.css' %}"-->
{% endblock %}
{% block title %} Registro de tiempos {% endblock %}
{% block tool %}
<div class="row">
  <div class="col s9 m9 tool offset-s1 offset-m1" id="tool">
    <div class="card horizontal">
      <div class="card-stacked">
        <div class="card-content">
          <div class="row">
          <div class="input-field col s4 m4" id="sel_empresa">

          </div>
          <div class="input-field col s4 m4">
          </div>
          <div class="input-field col s4 m4">

          </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block tabla %}
<thead>
  <tr>
    <th>Identificacion</th>
    <th>Nombre</th>
    <th>Apellido</th>
    <th>Hora de Inicio</th>
    <th>Horas transcuridas</th>
    <th>Finalizar turno</th>
  </tr>
</thead>
<tbody id="tab_emp">

</tbody>
{% endblock %}
{% block botones %}
<a class="btn-floating btn-large waves-effect waves-light orange darken-3 addempleado" href="/usuario/add/empleado/"><i class="material-icons ">add</i></a>
{% endblock %}
{% block paginacion %}
{% endblock %}
{% block dialogos %}
<!-- Modal Structure -->
  <div id="addempleado" class="modal modal-fixed-footer">
    <div class="modal-content">
      <h4>Registrar Trabajador</h4>
      <div id="contenido">

      </div>
    </div>
    <div class="modal-footer">
      <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Agree</a>
    </div>
  </div>
{% endblock %}

usuario/templates/usuario/indexSupervisor.html
{% extends 'Registered/base2.html' %}
{% load staticfiles %}
{% block title %}Supervisores{% endblock %}
{% block javascript %}

<script type="text/javascript" src="{% static 'Registered/js/jqueryform.js' %}"></script>
  <script type="text/javascript" src="{% static 'Registered/js/valid_form_ajax.js' %}"></script>
  <script type="text/javascript" src="{% static 'empresa/js/addsupervisor.js' %}"></script>
  <script type="text/javascript" src="{% static 'empresa/js/deletesupervisor.js' %}"></script>
  <script type="text/javascript" src="{% static 'empresa/js/editsupervisor.js' %}"></script>
  <script type="text/javascript" src="{% static 'empresa/js/listsupervisor.js' %}"></script>
{% endblock %}
{% block css %}
  <link rel="stylesheet" type="text/css" href="{% static 'operacion/css/listar_labores.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'empresa/css/empresa.css' %}">
{% endblock %}

{% block tool %}

<div class="row cajaIn caja scrolbx">
  <div class="col s10 m10 l10 ">
     <input placeholder="Busqueda por cualquier criterio" id="search" type="text" class="validate">
  </div>
  <div class="col s1 m1 l1 ">
     <a href="{% url 'empresa:add_tienda' %}" class="btn-floating btn-large waves-effect waves-light #4db6ac addtienda"><i class="material-icons" id="addtrabajador">add</i></a>
  </div>
</div>

{% endblock %}

{% block contenido %}
<div class="row cajaIn caja scrolbx scrolby">
  <div class="col s12 m12 l12" id="Tabla">
    <table class="highlight centered">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Apellido</th>
          <th>UserName</th>
          <th>Celular</th>
          <th>Empresas</th>
          <th>Opciones</th>
        </tr>
      </thead>
      <tbody id="tab_tiendas">

      </tbody>
    </table>
  </div>
</div>
{% endblock %}
{% block dialog %}

<!--**********************************************Agregar Tienda****************************************************-->
<div id="addtienda" class="modal modal-fixed-footer">
  <div class="modal-content">
    <h4>Registrar Tienda</h4>
    <div id="contenido">

    </div>
  </div>
  <div class="modal-footer">
    <a href="{% url 'empresa:add_tienda' %}" class="modal-action waves-effect waves-green btn-flat savetienda">Guardar</a>
    <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Cancelar</a>
  </div>
</div>

<!--*************************************************Editar Tienda***************************************************-->
<div id="edittienda" class="modal modal-fixed-footer">
  <div class="modal-content">
    <h4>Editar Tienda</h4>
    <div id="edit_contenido">

    </div>
  </div>
  <div class="modal-footer">
    <a href="#!" class="modal-action waves-effect waves-green btn-flat edit_modal_tienda">Modificar</a>
    <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Cancelar</a>
  </div>
</div>

<!--**********************************************Eliminar Tienda*****************************************************-->
<div id="deletetienda" class="modal modal-fixed-footer">
  <div class="modal-content">
    <h4>Eliminar Tienda</h4>
    <div id="cont_delete_mod">

    </div>
  </div>
  <div class="modal-footer">
    <a href="#!" class="modal-action waves-effect waves-green btn-flat delete_save_tienda">Si</a>
    <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">No</a>
  </div>
</div>

{% endblock %}

usuario/templates/usuario/listarempleados.html
{% extends 'Registered/base2.html' %}
{% load staticfiles %}
{% block title %}Listar empleados{% endblock %}
{% block javascript %}
  <!--script type="text/javascript" src="http://malsup.github.com/jquery.form.js"></script-->
  <script type="text/javascript" src="{% static 'Registered/js/jqueryform.js' %}"></script>
  <script type="text/javascript" src="{% static 'Registered/js/valid_form_ajax.js' %}"></script>
  <script type="text/javascript" src="{% static 'usuario/js/editempleado.js' %}"></script>
  <script type="text/javascript" src="{% static 'usuario/js/empleados.js' %}"></script>
  <script type="text/javascript" src="{% static 'usuario/js/addempleado.js' %}"></script>
  <script type="text/javascript" src="{% static 'usuario/js/deleteempleado.js' %}"></script>
{% endblock %}
{% block css %}
  <!--link rel="stylesheet" href="{% static 'usuario/css/listarempleado.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'operacion/css/listar_labores.css' %}"-->
{% endblock %}

{% block tool %}
  <div class="row cajaIn caja">
    <div class="col s4 m4 l4 ">
      <select id = "empresa" {% if not empresa %} disabled{% endif %}>
        <option value="0" disabled selected>{% if empresa %}Empresa{% else %} No Registros {% endif %}</option>
        {% if empresa %}
        {% for c in empresa %}
        <option value="{{ c.id }}">{{ c.first_name }}</option>
        {% endfor %}
        {% endif %}
      </select>    
    </div>
    <div class="col s4 m4 l4 ">
      <select id="ciudad" disabled>
        <option value="" disabled selected>Ciudad</option>
        <option value="1">Option 1</option>
        <option value="2">Option 2</option>
        <option value="3">Option 3</option>
      </select>    
    </div>
    <div class="col s4 m4 l4 ">
      <select id="tienda" disabled>
        <option value="" disabled selected>Tienda</option>
        <option value="1">Option 1</option>
        <option value="2">Option 2</option>
        <option value="3">Option 3</option>
      </select>    
    </div>
  </div>
  
  <div class="row cajaIn caja">
    <div class="col s10 m11 l11 ">
       <input placeholder="Busqueda" id="search" type="text" class="validate">
    </div>
    <div class="col s1 m1 l1 ">
       <a href="{% url 'usuario:add_empleado' %}"class="btn-floating btn-large waves-effect waves-light #4db6ac addempleado"><i class="material-icons" id="addtrabajador">add</i></a>
    </div>
  </div>  
{% endblock %}

{% block contenido %}
<div class="row cajaIn caja scrolbx scrolby">
  <div class="col s12 m12 l12" id="Tabla">
    <table class="highlight centered">
      <thead>
        <tr>
          <th>Empresa</th>
          <th>Ciudad</th>
          <th>Tienda</th>
          <th>Identificacion</th>
          <th>Nombre</th>
          <th>Apellidos</th>
          <th>Opciones</th>
        </tr>
      </thead>
      <tbody id="tab_emp">

      </tbody>
    </table>
  </div>
</div>
{% endblock %}
{% block dialog %}
<!--*******************************************************************************************************-->
<!--*****************************************AGREGAR EMPLEADO**********************************************-->
<!--*******************************************************************************************************-->
<div id="addempleado" class="modal modal-fixed-footer">
  <div class="modal-content">
    <h4>Registrar Trabajador</h4>
    <div id="contenido">

    </div>
  </div>
  <div class="modal-footer">
    <a href="#!" class="modal-action waves-effect waves-green btn-flat saveempleado">Guardar</a>
    <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Cancelar</a>
  </div>
</div>
<!--*******************************************************************************************************-->
<!--****************************************EDITAR EMPLEADO************************************************-->
<!--*******************************************************************************************************-->
<div id="editempleado" class="modal modal-fixed-footer">
  <div class="modal-content">
    <h4>Editar Trabajador</h4>
    <div id="edit_contenido">

    </div>
  </div>
  <div class="modal-footer">
    <a href="#!" class="modal-action waves-effect waves-green btn-flat edit_modal_empleado">Modificar</a>
    <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Cancelar</a>
  </div>
</div>
<!--*******************************************************************************************************-->
<!--*************************************ELIMINAR EMPLEADO*************************************************-->
<!--*******************************************************************************************************-->
<div id="deleteempleado" class="modal modal-fixed-footer">
  <div class="modal-content">
    <h4>Eliminar Trabajador</h4>
    <div id="cont_delete_mod">

    </div>
  </div>
  <div class="modal-footer">
    <a href="#!" class="modal-action waves-effect waves-green btn-flat delete_save_empleado">Si</a>
    <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">No</a>
  </div>
</div>
{% endblock %}