Registered/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
import settings
from django.conf.urls.static import static
import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^nested_admin/', include('nested_admin.urls')),
    url(r'^operacion/', include('operacion.urls',namespace='operacion')),
    url(r'^usuario/', include('usuario.urls',namespace='usuario')),
    url(r'^empresa/', include('empresa.urls',namespace='empresa')),
    url(r'^motorizado/', include('motorizado.urls',namespace='motorizado')),
    url(r'^reporte/', include('reporte.urls',namespace='reporte')),
    url(r'^$', login_required(views.Index.as_view()),name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

empresa/urls.py
from django.conf.urls import url
import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required


#Manejo de empresa
urlpatterns = [
    url(r'list/empresa/$', login_required(views.ListEmpresa.as_view()), name='list_empresa'),
    url(r'add/empresa/$', login_required(views.AddEmpresa.as_view()), name='add_empresa'),
    url(r'edit/empresa/(?P<pk>\d+)/$', login_required(views.EditEmpresa.as_view()), name='edit_empresa'),
    url(r'change/pass/empresa/$', login_required(views.SetPassWordEmpresa.as_view()), name='change_pass_empresa'),
    url(r'delete/empresa/(?P<pk>\d+)/$', login_required(views.DeleteEmpresa.as_view()), name='delete_pass_empresa'),
]

#Manejo de tienda
urlpatterns += [
    url(r'list/tienda/$', login_required(views.ListTienda.as_view()), name='list_tienda'),
    url(r'add/tienda/$', login_required(views.AddTienda.as_view()), name='add_tienda'),
    url(r'edit/tienda/(?P<pk>\d+)/$', login_required(views.AddTienda.as_view()), name='edit_tienda'),
    url(r'delete/tienda/(?P<pk>\d+)/$', login_required(views.DeleteTienda.as_view()), name='delete_pass_tienda'),
]

#Manejo de tienda
urlpatterns += [
    url(r'list/supervisor/$', login_required(views.ListSupervisor.as_view()), name='list_supervisor'),
    url(r'add/supervisor/$', login_required(views.AddSupervisor.as_view()), name='add_supervisor'),
    url(r'edit/supervisor/(?P<pk>\d+)/$', login_required(views.EditSupervisor.as_view()), name='edit_supervisor'),
    url(r'delete/supervisor/(?P<pk>\d+)/$', login_required(views.DeleteSupervisor.as_view()), name='delete_pass_supervisor'),
]

#Manejo de ciudad
urlpatterns += [
    url(r'list/ciudad/$', login_required(views.ListCiudad.as_view()), name='list_ciudad'),
]

#vista
urlpatterns += [
    url(r'indexEmpresas/$',login_required(views.Empresas.as_view()), name='index_empresas'),
]

#vista Tiendas
urlpatterns += [
    url(r'indexTienda/$',login_required(views.Tiendas.as_view()), name='index_tiendas'),
]

#vista Supervisores
urlpatterns += [
    url(r'indexsupervisor/$',login_required(views.Supervisores.as_view()), name='index_supervisor'),
]

motorizado/urls.py
from django.conf.urls import url
import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
#Inicio de session
urlpatterns = [
    url(r'^motos/$',login_required(TemplateView.as_view(template_name='motorizado/motos.html')), name='infomoto'),
    url(r'^add/moto/$',login_required(views.AddMoto.as_view()) ,name='add_moto'),
    url(r'^edit/moto/(?P<pk>\d+)/$',login_required(views.AddMoto.as_view()) ,name='edit_moto'),
    url(r'^delete/moto/(?P<pk>\d+)/$',login_required(views.DeleteMoto.as_view()) ,name='delete_moto'),
    url(r'^list/moto/',login_required(views.ListMoto.as_view()) ,name='lis_moto'),
    url(r'^list/motorizado/',login_required(views.ListMotorizados.as_view()) ,name='lis_motorizado'),
]

operacion/urls.py
from django.conf.urls import url
import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

'''urlpatterns = [
    url(r'login/$', views.custom_login, {'template_name': 'usuario/login.html'}, name='user-login'),
    url(r'logout/$', views.custom_logout, {'next_page': '/', }, name='user-logout'),
]'''

#formularios configuracion
urlpatterns = [
    url(r'^configuraciones/$',login_required(TemplateView.as_view(template_name='operacion/configuraciones.html')), name='configuraciones'),
    url(r'add/configuracion/$',login_required(views.AddConfiguracionWS.as_view()) ,name='add_conf'),
    url(r'edit/configuracion/(?P<pk>\d)/$',login_required(views.AddConfiguracion.as_view()) ,name='edit_conf'),
    url(r'list/configuracion/$',login_required(views.ListConfiguracion.as_view()) ,name='list_conf'),
]


#formularios configuracion
urlpatterns += [
    url(r'add/labor/$',login_required(views.AddLabor.as_view()) ,name='add_labor'),
    url(r'edit/labor/',login_required(views.EditLabor.as_view()) ,name='edit_labor'),
    url(r'delete/labor/(?P<pk>\d)/$',login_required(views.DeleteLabor.as_view()) ,name='delete_labor'),
    url(r'list/labor/$',login_required(views.ListLabor.as_view()) ,name='list_labor'),
]

#funcionalidad de adicional labor
urlpatterns += [
    url(r'labores/$',views.Labores.as_view() ,name='labores'),
    url(r'movil/trabajos/$',login_required(views.MobilLabore.as_view()) ,name='movil_labores'),
    url(r'ws/labor/$',login_required(views.AddWsLabor.as_view()) ,name='ws_labor'),
]

#funciones de la funcion de Observaciones
urlpatterns += [
    url(r'index/observacion/$',login_required(TemplateView.as_view(template_name='operacion/observaciones.html')),name='index_observacion'),
    url(r'add/observacion/$',login_required(views.AddObservacion.as_view()),name='add_observacion'),
    url(r'edit/observacion/(?P<pk>)/$',login_required(views.AddObservacion.as_view()),name='edit_observacion'),
    url(r'delete/observacion/(?P<pk>)/$',login_required(views.DeleteObservacion.as_view()),name='delete_observacion'),
    url(r'list/observacion/$',login_required(views.ListObservacion.as_view()),name='list_observacion'),
    url(r'validar/observacion/(?P<pk>)/$',login_required(views.ValidarObservacion.as_view()),name='valid_observacion'),
]

usuario/urls.py
from django.conf.urls import url
import views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

#empleado
urlpatterns = [
    url(r'^login/empleado/$',login_required(views.LoginEmpleado.as_view()) ,name='login_empleado'),
    url(r'^add/empleado/$',login_required(views.AddEmpleado.as_view()) ,name='add_empleado'),
    url(r'^edit/empleado/(?P<pk>\d+)/$',login_required(views.EditEmpleado.as_view()) ,name='edit_empleado'),
    url(r'^delete/empleado/(?P<pk>\d+)/$',login_required(views.DeleteEmpleado.as_view()) ,name='delete_empleado'),
    url(r'^list/empleado/',login_required(views.ListEmpleado.as_view()) ,name='lis_empleado'),
    url(r'^list/empleados/',login_required(views.ListEmpleados.as_view()) ,name='list_empleados'),
    url(r'^change/pass/empleados/',login_required(views.SetPassWordEmpleado.as_view()) ,name='set_pass_empleado'),
    url(r'^is/login/administrador/$',login_required(views.IsLogin.as_view()) ,name='is_login_admin'),
]


#direccionamientos del empleado a nivel de vista
urlpatterns += [
    url(r'^view/empleados/$',login_required(views.GeneralCliente.as_view()), name='view_empleados'),
]


#Inicio de session
urlpatterns += [
    url(r'^login/$',views.Login.as_view(), name='login'),
    url(r'^logout/$',views.Logout.as_view(), name='logout'),
]


# manejo de usuario de empleados escritorio
urlpatterns += [
    url(r'^empleados/$',login_required(views.Empleados.as_view()), name='esc_lis_empleados'),
]


# registro de supervisores
urlpatterns += [
    url(r'^supervisores/$',login_required(views.Supervisores.as_view()), name='supervisoress'),
]

operacion/models.py
# -*- coding: utf-8 -*-
#cuve os
from __future__ import unicode_literals

from django.db import models
from empresa import models as empresa
from empresa.models import Ciudad
from usuario import models as usuario

# Create your models here.

class DiaSemana(models.Model):
    nombre = models.CharField(max_length=30)
    valor = models.IntegerField()
    estado = models.BooleanField(default=True)

    def __unicode__(self):
        return u'%s'%self.nombre

    #end def
    def __str__(self):
        return u'%s'%self.nombre
    #end def

    class Meta:
        verbose_name = 'Dia de la semana'
        verbose_name_plural = 'Dias de la semana'
    #end class
#end class


class PrecioDefecto(models.Model):
    empresa = models.ForeignKey(empresa.Empresa)
    ciudad = models.ForeignKey(Ciudad)
    valor = models.FloatField()
    estado = models.BooleanField(default=True)

    def __unicode__(self):
        return u'%s'%self.empresa.first_name
    # end def

    def __str__(self):
        return u'%s'%self.empresa.first_name
    # end def

    class Meta:
        verbose_name ='Configuracion pago por defecto  tienda'
        verbose_name_plural ='Configuraciones pago por defecto tienda'
    #end class



class Configuracion(models.Model):
    empresa = models.ForeignKey(empresa.Empresa)
    ciudad = models.ForeignKey(Ciudad)
    valor = models.FloatField()
    inicio = models.TimeField(editable=True, null=True)
    fin = models.TimeField(editable=True, null=True)
    dias = models.ManyToManyField(DiaSemana)
    estado = models.BooleanField(default=True)

    def __unicode__(self):
        return u'%s'%self.empresa.first_name
    # end def

    def __str__(self):
        return u'%s'%self.empresa.first_name
    # end def

    class Meta:
        verbose_name ='Configuracion pago por tienda'
        verbose_name_plural ='Configuraciones pago por tienda'
    #end class
#end class


class Calendario(models.Model):
    year = models.IntegerField(verbose_name='Año')
    estado = models.BooleanField(default=True)

    def __unicode__(self):
        return u'%d'%self.year
    # end class

    def __str__(self):
        return u'%d'%self.year
    # end class

    class Meta:
        verbose_name ='Calendario'
        verbose_name_plural ='Calendarios'
    #end class
#end class


class Dia(models.Model):
    year = models.ForeignKey(Calendario)
    dia = models.DateField()
    estado= models.BooleanField(default=True)

    def __unicode__(self):
        return u'%d-%d-%d'%(self.dia.day,self.dia.month,self.dia.year)
    # end class

    def __str__(self):
        return u'%d-%d-%d'%(self.dia.day,self.dia.month,self.dia.year)
    # end class

    class Meta:
        verbose_name ='Dia'
        verbose_name_plural ='Dias'
    #end class
#end class


class Labor(models.Model):
    empleado = models.ForeignKey(usuario.Empleado)
    ini = models.DateTimeField(blank=True,null=True, editable=True)
    fin = models.DateTimeField(blank=True,null=True)
    estado = models.BooleanField(default=True)
    cerrado = models.BooleanField(default=False)

    def __unicode__(self):
        return u'%s %s'%(self.empleado.first_name,self.empleado.last_name)
    # end class

    def __str__(self):
        return u'%s %s'%(self.empleado.first_name,self.empleado.last_name)
    # end class

    class Meta:
        verbose_name ='Labor'
        verbose_name_plural ='Labores'
    #end class
#end class


class PagoLabor(models.Model):
    labor = models.ForeignKey(Labor)
    ini = models.CharField(max_length=100, verbose_name="Hora de inicio", null=True,blank=True)
    fin = models.CharField(max_length=100, verbose_name="Hora de fin", null=True,blank=True)
    precio = models.FloatField(default=0)
    hora = models.FloatField(default=0)

    def __unicode__(self):
        return u'%s %s'%(self.labor.empleado.first_name,self.labor.empleado.last_name)
    # end class

    def __str__(self):
        return u'%s %s'%(self.labor.empleado.first_name,self.labor.empleado.last_name)
    # end class

    class Meta:
        verbose_name ='Pago Labor'
        verbose_name_plural ='Pago Labores'
    #end class
#end class


class Observacion(models.Model):
    empleado = models.ForeignKey(usuario.Empleado, verbose_name='Domiciliario')
    tienda = models.ForeignKey(empresa.Tienda, blank=True, null=True)
    observacion = models.CharField(max_length=800, null=True, blank=True)
    atendido = models.BooleanField(default=False)
    estado= models.BooleanField(default=True)

    def __init__(self):
        return u'%s %s- %s'%(self.empleado.first_name, self.empleado.last_name, self.tienda.nombre)
    #end def

    def __str__(self):
        return u'%s %s- %s'%(self.empleado.first_name, self.empleado.last_name, self.tienda.nombre)
    #end def

    class Meta:
        verbose_name = 'Observacion'
        verbose_name_plural = 'Observaciones'
    #end class
#end class

operacion/templates/operacion/addconfig.html
<form action="" method="post" id="add_form">
  {% csrf_token %}
    {{form.as_p}}
</form>

operacion/templates/operacion/addconig.html
<form action="" method="post" id="add_form">
  {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Send message" />
</form>

operacion/templates/operacion/addlabor.html
<form action="" method="post">
  {% csrf_token %}
    {{form.as_p}}
</form>

operacion/templates/operacion/addlaborview.html
<form action="" method="post">
  {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Send message" />
</form>

operacion/templates/operacion/addobservacion.html
<form action="" method="post">
  {% csrf_token %}
    {{form.as_p}}
</form>

operacion/templates/operacion/home.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>home</title>
</head>
<body>
	
</body>
</html>

operacion/templates/operacion/listado_labores.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
	    <meta http-equiv="X-UA-Compatible" content="ie=edge">
	    <script type="text/javascript" src="{% static 'Registered/js/jquery-2.1.1.min.js' %}"></script>
	    <link rel="stylesheet" href="{% static 'Registered/css/materialize.min.css' %}">
	    <link rel="stylesheet" type="text/css" href="{% static 'operacion/css/listar_labores.css' %}">
	    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
	    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
		<!--link href="{% static 'Registered/css/estilo.css' %}" rel="stylesheet">
		<link href="{% static 'Registered/css/home.css' %}" rel="stylesheet"-->
	    <script src="{% static 'Registered/js/materialize.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'operacion/js/cerrarLabor.js' %}"></script>
		<script type="text/javascript" src="{% static 'operacion/js/listar_labores.js' %}"></script>
		<script type="text/javascript" src="{% static 'operacion/js/labores.js' %}"></script>
		<script type="text/javascript" src="{% static 'operacion/js/modallabor.js' %}"></script>
		<title>Listado de labores</title>
	</head>
	<body>
		<header>
		    <div class="row">
		        <div class="col s6 m4 l2 offset-s1 offset-m1 offset-l1">
		          	<div class="row">
			            <a href="#">
				            <div class="col s3 m3 l3">
				              <center><i class="material-icons" id="logeoT">phonelink_lock</i></center>
				            </div>
				            <div class="col s6 m6 l6">
				              <center><p id="titulo">Registered</p></center>
				            </div>
			            </a>
		         	</div>
		        </div>

		        <div class="col s2 m4 l7 "></div>
		        <div class="col s3 m2 l1">
		        	<center><a href="{% url 'usuario:logout' %}"><i class="material-icons" id="close">input</i></a></center>
		        </div>
		    </div><!--end div row-->
		</header>

		<div class="container filtro">
			<div class="row">
				<div class="col s10 m10 l11 ">
				    <input placeholder="Busqueda" id="busqueda" type="text" class="validate">
			    </div>
			    <div class="col s1 m1 l1 ">
				    <a class="btn-floating btn-large waves-effect waves-light #4db6acn addlabormodal"><i class="material-icons" >add</i></a>
		        </div>
			</div>
   		</div>

		<section>
			<div class="container">
				<div class="row" id="labores">
					<!--Js Codigo a mostrar en la tabla-->
				</div><!--end row-->
	        </div>
		</section>
		<div id="mensaje_empleado" class="modal modal-fixed-footer">
				<div class="modal-content">
					<h4>Todos los motorizados se encuentran actualmente, en el punto de venta.</h4>
				</div>
				<div class="modal-footer">
					<a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Aceptar</a>
				</div>
		</div>

		<div id="addlabor" class="modal modal-fixed-footer">
			<div class="modal-content row">
				<h4>Registrar Turno</h4>
				<div id="contenido">
					<form class="col s12" id="form_labor" action="{% url 'operacion:ws_labor' %}">
						<div class="row">
							<div class="input-field col s12">
							    <select name="empleado" id="empleado">
								</select>

							    <label>Empleados</label>
							</div>

							<div class="row">
								<div class="input-field col s12 m8">
									<label for="mensaje"></label>
								</div>
							</div>
						</div>
					</form>
				</div>
			</div>
			<div class="modal-footer">
						<a href="{% url 'usuario:login_empleado' %}" class="modal-action waves-effect waves-green btn-flat addlabor">Iniciar Sesión</a>
						<a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Cancelar</a>
			</div>
		</div>

				<div id="cerrarlaborc" class="modal modal-fixed-footer">
					<div class="modal-content row">
						<h4>Cerrar Turno</h4>
						<div id="contenidoc">
							<form class="col s12" id="form_laborc" action="{% url 'operacion:ws_labor' %}">
									<div class="row">
										<div class="input-field col s12 m8">
											<input placeholder="Placeholder" id="userc" type="text" class="validate" disabled>
											<label for="userc">Empleado</label>
										</div>
									<div class="row">
										<div class="input-field col s12 m8">
											<!--input id="passwordc" type="password" class="validate">
											<label for="passwordc">Contraseña</label-->
										</div>
									</div>
									<div class="row">
										<div class="input-field col s12 m8">
											<label for="mensajec"></label>
										</div>
									</div>
						</div>
					</form>
						</div>
					</div>
					<div class="modal-footer">
						<a href="{% url 'usuario:is_login_admin' %}" class="modal-action waves-effect waves-green btn-flat editlabor sendLabor">Aceptar</a>
						<a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Cancelar</a>
					</div>
				</div>
	</body>
</html>

operacion/templates/operacion/observaciones.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
	    <meta http-equiv="X-UA-Compatible" content="ie=edge">
	    <script type="text/javascript" src="{% static 'Registered/js/jquery-2.1.1.min.js' %}"></script>
	    <link rel="stylesheet" href="{% static 'Registered/css/materialize.min.css' %}">
	    <link rel="stylesheet" type="text/css" href="{% static 'operacion/css/listar_labores.css' %}">
	    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
	    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
	    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
		<!--link href="{% static 'Registered/css/estilo.css' %}" rel="stylesheet">
		<link href="{% static 'Registered/css/home.css' %}" rel="stylesheet"-->
	    <script src="{% static 'Registered/js/materialize.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'operacion/js/cerrarLabor.js' %}"></script>
		<script type="text/javascript" src="{% static 'operacion/js/listar_labores.js' %}"></script>
		<script type="text/javascript" src="{% static 'operacion/js/labores.js' %}"></script>
		<script type="text/javascript" src="{% static 'operacion/js/modallabor.js' %}"></script>
		<title>Listado de labores</title>
	</head>
	<body>
		<header>
		    <div class="row">
		        <div class="col s6 m4 l2 offset-s1 offset-m1 offset-l1">
		          	<div class="row">
			            <a href="{% url 'index' %}">
				            <div class="col s3 m3 l3">
				              <center><i class="material-icons" id="logeoT">phonelink_lock</i></center>
				            </div>
				            <div class="col s6 m6 l6">
				              <center><p id="titulo">Registered</p></center>
				            </div>
			            </a>
		         	</div>
		        </div>

		        <div class="col s2 m4 l7 "></div>
		        <div class="col s3 m2 l1">
		        	<center><a href="{% url 'usuario:logout' %}"><i class="material-icons" id="close">input</i></a></center>
		        </div>
		    </div><!--end div row-->
		</header>

		<!--div class="container filtro" style="margin-bottom: 20px;">
			<div class="row">
				<div class="col s10 m11 l11 ">
					<input placeholder="Busqueda" id="busqueda" type="text" class="validate">
				</div>
				<div class="col s1 m1 l1 ">
					<a class="btn-floating btn-large waves-effect waves-light #4db6acn addlabormodal"><i class="material-icons" >add</i></a>
				</div>
			</div>
		</div-->
		<div class="container filtro">
			<div class="row">
				<div class="col s10 m10 l11 ">
				    <input placeholder="Busqueda" id="busqueda" type="text" class="validate">
			    </div>
			    <div class="col s1 m1 l1 ">
				    <a class="btn-floating btn-large waves-effect waves-light #4db6acn addlabormodal"><i class="material-icons" >add</i></a>
		        </div>
			</div>
   		</div>

		<section>
			<div class="container">
				<div class="row" id="labores">
					<!--Js Codigo a mostrar en la tabla-->
				</div><!--end row-->
	        </div>
<<<<<<< HEAD
        </section>
				<div id="mensaje_empleado" class="modal modal-fixed-footer">
						<div class="modal-content">
							<h4>No existen domiciliarios</h4>
							<p>Los domiciliarios asignados se encuentram en labor,
							    debe ponerse en contacto con su proveedor.</p>
						</div>
						<div class="modal-footer">
							<a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Aceptar</a>
						</div>
					</div>
				<div id="addlabor" class="modal modal-fixed-footer">
					<div class="modal-content row">
						<h4>Registrar Turno</h4>
						<div id="contenido">
							<form class="col s12" id="form_labor" action="{% url 'operacion:ws_labor' %}">
									<div class="row">
										<div class="input-field col s12">
									    <select name="empleado" id="empleado">
									      <option value="0" disabled selected>Seleccione Trabajador</option>
=======
		</section>

		<div id="addlabor" class="modal modal-fixed-footer">
			<div class="modal-content row">
				<h4>Registrar Turno</h4>
				<div id="contenido">
					<form class="col s12" id="form_labor" action="{% url 'operacion:ws_labor' %}">
						<div class="row">
							<div class="input-field col s12">
							    <select name="empleado" id="empleado">
		    				        <option value="0" disabled selected>Seleccione Trabajador</option>
>>>>>>> fc9f5bc04c7e88100fe8fcda4a034cbe6130e9cf
												{% for e in empleados %}
									<option value="{{ e.empleado.id}}">{{ e.empleado__first_name }} {{ e.empleado.last_name }}</option>
												{% endfor %}
								</select>

							    <label>Empleados</label>
							</div>

							<div class="input-field col s12 m8">
								<input placeholder="usuario" id="user" type="text" class="validate" value="{{ usuario }}">
								<label for="first_name">Usuario</label>
							</div>

							<div class="row">
								<div class="input-field col s12 m8">
									<input id="password" type="password" class="validate" placeholder="contraseña">
									<label for="password">Contraseña</label>
								</div>
							</div>

							<div class="row">
								<div class="input-field col s12 m8">
									<label for="mensaje"></label>
								</div>
							</div>
						</div>
					</form>
				</div>
<<<<<<< HEAD

				<div id="cerrarlaborc" class="modal modal-fixed-footer">
					<div class="modal-content row">
						<h4>Cerrar Turno</h4>
						<div id="contenidoc">
							<form class="col s12" id="form_laborc" action="{% url 'operacion:ws_labor' %}">
									<div class="row">
										<div class="input-field col s12 m8">
											<input placeholder="Placeholder" id="userc" type="text" class="validate" disabled>
											<label for="userc">Usuario</label>
										</div>
									<div class="row">
										<div class="input-field col s12 m8">
											<input id="passwordc" type="password" class="validate">
											<label for="passwordc">Contraseña</label>
										</div>
									</div>
									<div class="row">
										<div class="input-field col s12 m8">
											<label for="mensajec"></label>
										</div>
									</div>
						</div>
					</form>
						</div>
					</div>
					<div class="modal-footer">
						<a href="{% url 'usuario:is_login_admin' %}" class="modal-action waves-effect waves-green btn-flat editlabor sendLabor">Iniciar Sesión</a>
						<a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Cancelar</a>
					</div>
				</div>

=======
			</div>

			<div class="modal-footer">
				<a href="{% url 'usuario:login_empleado' %}" class="modal-action waves-effect waves-green btn-flat addlabor">Iniciar Sesión</a>
				<a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Cancelar</a>
			</div>

		</div>

		<div id="cerrarlaborc" class="modal modal-fixed-footer">
			<div class="modal-content row">
				<h4>Cerrar Turno</h4>
				<div id="contenidoc">
					<form class="col s12" id="form_laborc" action="{% url 'operacion:ws_labor' %}">
						<div class="row">
							<div class="input-field col s12 m8">
								<input placeholder="Placeholder" id="userc" type="text" class="validate" disabled>
								<label for="userc">Usuario</label>
							</div>

							<div class="row">
								<div class="input-field col s12 m8">
									<input id="passwordc" type="password" class="validate">
									<label for="passwordc">Contraseña</label>
								</div>
							</div>

							<div class="row">
								<div class="input-field col s12 m8">
									<label for="mensajec"></label>
								</div>
							</div>
						</div>
					</form>
				</div>
			</div>
			<div class="modal-footer">
				<a href="{% url 'usuario:login_empleado' %}" class="modal-action waves-effect waves-green btn-flat editlabor sendLabor">Iniciar Sesión</a>
				<a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat ">Cancelar</a>
			</div>
		</div>
>>>>>>> fc9f5bc04c7e88100fe8fcda4a034cbe6130e9cf
	</body>
</html>